version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Nischal@2006
      MYSQL_DATABASE: chatapp
    ports:
      - "3307:3306"

      - name: Build Docker image
        run: docker build -f path/to/your/Dockerfile .
