version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: chatapplication-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nischal@2006
      MYSQL_DATABASE: chatapp
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: chatapplication-backend-1
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: Nischal@2006
      DB_NAME: chatapp
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: chatapplication-frontend-1
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
